package database

const (
	insertOrderQuery     = "INSERT INTO ORDERS(ID, PRICE, HASHRATE, START_TIME, STATUS, ACTUAL_STEP) VALUES (:ID, :PRICE, :HASHRATE, :START_TIME, :STATUS, :ACTUAL_STEP)"
	insertTestOrderQuery = "INSERT INTO ORDERS(ID, STATUS, ACTUAL_STEP) VALUES (:ID, :STATUS, :ACTUAL_STEP)"
	insertDealsQuery     = "INSERT INTO DEALS(ID, STATUS, PRICE, ASK_ID, BID_ID, DEPLOY_STATUS, CHANGE_REQUEST_STATUS) VALUES (:ID, :STATUS, :PRICE, :ASK_ID, :BID_ID, :DEPLOY_STATUS, :CHANGE_REQUEST_STATUS )"
	insertTokenQuery     = "INSERT INTO TOKENS (TOKEN_ID, NAME, USD_PRICE, NET_HASHES_SEC, BLOCK_TIME, BLOCK_REWARD,  PROFIT_PER_MONTH_USD, DATE_TIME) VALUES (:TOKEN_ID, :NAME, :USD_PRICE, :NET_HASHES_SEC, :BLOCK_TIME, :BLOCK_REWARD, :PROFIT_PER_MONTH_USD, :DATE_TIME)"
	insertPoolsQuery     = "INSERT INTO POOLS (DEAL_ID, POOL_ID, W_REP_HASH, W_AVG_HASH, BAD_GUY, ITERATIONS, TIME_START, TIME_UPDATE) VALUES (:DEAL_ID, :POOL_ID, :W_REP_HASH, :W_AVG_HASH, :BAD_GUY, :ITERATIONS, :TIME_START, :TIME_UPDATE)"
	insertBlackListQuery = "INSERT INTO BLACKLIST (MASTER_ID, FAIL_SUPPLIER_ID, BAN_STATUS, DEAL_ID) VALUES (:MASTER_ID, :FAIL_SUPPLIER_ID, :BAN_STATUS, :DEAL_ID )"

	updateOrdersQuery              = "UPDATE ORDERS SET STATUS = ?	 WHERE ID = ?"
	updateDeployStatusDealQuery    = "UPDATE DEALS SET DEPLOY_STATUS = ?	 WHERE ID = ?"
	updateDeployAndDealStatusQuery = "UPDATE DEALS SET DEPLOY_STATUS = ?, STATUS = ? WHERE ID = ?"
	updateDealCRPriceQuery         = "UPDATE DEALS SET CHANGE_REQUEST_STATUS=?, PRICE =? where ID = ?"
	updateDealCRQuery              = "UPDATE DEALS SET CHANGE_REQUEST_STATUS=? where ID = ?"
	updateStatusInPoolQuery        = "UPDATE POOLS SET BAD_GUY = ?, TIME_UPDATE = ? WHERE DEAL_ID = ?"
	updateReportedHashrateQuery    = "UPDATE POOLS SET W_REP_HASH = ?, TIME_UPDATE = ? WHERE DEAL_ID = ?"
	updateAvgPoolQuery             = "UPDATE POOLS SET W_AVG_HASH = ?, TIME_UPDATE = ? WHERE DEAL_ID = ?"
	updateBlacklistQuery           = "UPDATE BLACKLIST SET BAN_STATUS = ? WHERE MASTER_ID = ?"
	updateIterationPoolQuery       = "UPDATE POOLS SET ITERATIONS = ? WHERE DEAL_ID = ?"

	updateDealDeployStatusQuery = "UPDATE DEALS SET DEPLOY_STATUS =? WHERE ID = ?"

	selectCountFromQuery                  = "SELECT COUNT(ID) AS count FROM ORDERS"
	selectSupplierIDFromBlackListQuery    = "SELECT FAIL_SUPPLIER_ID FROM BLACKLIST WHERE FAIL_SUPPLIER_ID = ?"
	selectMasterIDFromBlackListQuery      = "SELECT MASTER_ID FROM BLACKLIST WHERE MASTER_ID = ?"
	selectWorkerIDFromPoolQuery           = "SELECT DEAL_ID from POOLS WHERE DEAL_ID = ?"
	selectSupplierCountFromBlackListQuery = "SELECT COUNT(FAIL_SUPPLIER_ID) as count from BLACKLIST WHERE MASTER_ID = ?"
	selectLastActualStepQuery             = "SELECT MAX(ACTUAL_STEP) AS max FROM ORDERS WHERE STATUS = 2"
	selectChangeRequestStatusQuery        = "SELECT CHANGE_REQUEST_STATUS from DEALS WHERE ID = ?"
	selectDeployStatusQuery               = "SELECT DEPLOY_STATUS from DEALS WHERE ID = ?"

	selectAllOrdersQuery  = "SELECT * FROM ORDERS"
	selectAllDealsQuery   = "SELECT * FROM DEALS"
	selectAllWorkersQuery = "SELECT * FROM POOLS"

	createBlacklistTableSQL = `
	CREATE TABLE IF NOT EXISTS BLACKLIST(
		MASTER_ID,
		FAIL_SUPPLIER_ID,
		BAN_STATUS,
		DEAL_ID
	);`

	createDealsTableSQL = `
	CREATE TABLE IF NOT EXISTS DEALS(
		ID INT NOT NULL UNIQUE,
		STATUS TEXT NOT NULL ,
		PRICE INT NOT NULL,
		ASK_ID INT NOT NULL,
		BID_ID INT NOT NULL,
		DEPLOY_STATUS INT NOT NULL,
		CHANGE_REQUEST_STATUS INT NOT NULL
	);`

	createOrdersTableSQL = `
	CREATE TABLE IF NOT EXISTS ORDERS(
		ID INT NOT NULL UNIQUE,
		PRICE INT NOT NULL,
		HASHRATE INT NOT NULL,
		START_TIME DATETIME NOT NULL,
		STATUS INT NOT NULL,
		ACTUAL_STEP FLOAT NOT NULL
	);`

	createTokensTableSQL = `
	CREATE TABLE IF NOT EXISTS TOKENS (
		TOKEN_ID TEXT NOT NULL,
		NAME TEXT NOT NULL,
		USD_PRICE FLOAT NOT NULL,
		NET_HASHES_SEC FLOAT NOT NULL,
		BLOCK_TIME INT NOT NULL,
		BLOCK_REWARD FLOAT NOT NULL,
		PROFIT_PER_MONTH_USD FLOAT NOT NULL,
		DATE_TIME DATETIME NOT NULL
	);`

	createPoolsTableSQL = `
	CREATE TABLE IF NOT EXISTS POOLS (
		DEAL_ID TEXT NOT NULL UNIQUE,
		POOL_ID TEXT NOT NULL,
		W_REP_HASH FLOAT NOT NULL,
		W_AVG_HASH FLOAT NOT NULL,
		BAD_GUY INT NOT NULL,
		ITERATIONS INT NOT NULL, 
		TIME_START DATETIME NOT NULL,
		TIME_UPDATE DATETIME NOT NULL
	);`
)
