// Code generated by protoc-gen-go. DO NOT EDIT.
// source: miner.proto

/*
Package miner is a generated protocol buffer package.

It is generated from these files:
	miner.proto

It has these top-level messages:
	PingRequest
	PingReply
	InfoRequest
	InfoReply
	HandshakeRequest
	HandshakeReply
	StartRequest
	StartReply
	StopRequest
	StopReply
*/
package miner

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingReply struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *PingReply) Reset()                    { *m = PingReply{} }
func (m *PingReply) String() string            { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()               {}
func (*PingReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type InfoRequest struct {
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InfoReply struct {
}

func (m *InfoReply) Reset()                    { *m = InfoReply{} }
func (m *InfoReply) String() string            { return proto.CompactTextString(m) }
func (*InfoReply) ProtoMessage()               {}
func (*InfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type HandshakeRequest struct {
	Hub string `protobuf:"bytes,1,opt,name=hub" json:"hub,omitempty"`
}

func (m *HandshakeRequest) Reset()                    { *m = HandshakeRequest{} }
func (m *HandshakeRequest) String() string            { return proto.CompactTextString(m) }
func (*HandshakeRequest) ProtoMessage()               {}
func (*HandshakeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HandshakeRequest) GetHub() string {
	if m != nil {
		return m.Hub
	}
	return ""
}

type HandshakeReply struct {
	Miner string `protobuf:"bytes,1,opt,name=miner" json:"miner,omitempty"`
}

func (m *HandshakeReply) Reset()                    { *m = HandshakeReply{} }
func (m *HandshakeReply) String() string            { return proto.CompactTextString(m) }
func (*HandshakeReply) ProtoMessage()               {}
func (*HandshakeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HandshakeReply) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

type StartRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Registry string `protobuf:"bytes,2,opt,name=registry" json:"registry,omitempty"`
	Image    string `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StartRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StartRequest) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

func (m *StartRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type StartReply struct {
	Container string                     `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	Ports     map[string]*StartReplyPort `protobuf:"bytes,2,rep,name=Ports" json:"Ports,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *StartReply) Reset()                    { *m = StartReply{} }
func (m *StartReply) String() string            { return proto.CompactTextString(m) }
func (*StartReply) ProtoMessage()               {}
func (*StartReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StartReply) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *StartReply) GetPorts() map[string]*StartReplyPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

type StartReplyPort struct {
	IP   string `protobuf:"bytes,1,opt,name=IP" json:"IP,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
}

func (m *StartReplyPort) Reset()                    { *m = StartReplyPort{} }
func (m *StartReplyPort) String() string            { return proto.CompactTextString(m) }
func (*StartReplyPort) ProtoMessage()               {}
func (*StartReplyPort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *StartReplyPort) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *StartReplyPort) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type StopRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StopRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StopReply struct {
}

func (m *StopReply) Reset()                    { *m = StopReply{} }
func (m *StopReply) String() string            { return proto.CompactTextString(m) }
func (*StopReply) ProtoMessage()               {}
func (*StopReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*PingRequest)(nil), "miner.PingRequest")
	proto.RegisterType((*PingReply)(nil), "miner.PingReply")
	proto.RegisterType((*InfoRequest)(nil), "miner.InfoRequest")
	proto.RegisterType((*InfoReply)(nil), "miner.InfoReply")
	proto.RegisterType((*HandshakeRequest)(nil), "miner.HandshakeRequest")
	proto.RegisterType((*HandshakeReply)(nil), "miner.HandshakeReply")
	proto.RegisterType((*StartRequest)(nil), "miner.StartRequest")
	proto.RegisterType((*StartReply)(nil), "miner.StartReply")
	proto.RegisterType((*StartReplyPort)(nil), "miner.StartReply.port")
	proto.RegisterType((*StopRequest)(nil), "miner.StopRequest")
	proto.RegisterType((*StopReply)(nil), "miner.StopReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Miner service

type MinerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoReply, error)
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeReply, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopReply, error)
}

type minerClient struct {
	cc *grpc.ClientConn
}

func NewMinerClient(cc *grpc.ClientConn) MinerClient {
	return &minerClient{cc}
}

func (c *minerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := grpc.Invoke(ctx, "/miner.Miner/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoReply, error) {
	out := new(InfoReply)
	err := grpc.Invoke(ctx, "/miner.Miner/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeReply, error) {
	out := new(HandshakeReply)
	err := grpc.Invoke(ctx, "/miner.Miner/Handshake", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error) {
	out := new(StartReply)
	err := grpc.Invoke(ctx, "/miner.Miner/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopReply, error) {
	out := new(StopReply)
	err := grpc.Invoke(ctx, "/miner.Miner/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Miner service

type MinerServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Info(context.Context, *InfoRequest) (*InfoReply, error)
	Handshake(context.Context, *HandshakeRequest) (*HandshakeReply, error)
	Start(context.Context, *StartRequest) (*StartReply, error)
	Stop(context.Context, *StopRequest) (*StopReply, error)
}

func RegisterMinerServer(s *grpc.Server, srv MinerServer) {
	s.RegisterService(&_Miner_serviceDesc, srv)
}

func _Miner_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/miner.Miner/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/miner.Miner/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/miner.Miner/Handshake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/miner.Miner/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/miner.Miner/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Miner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "miner.Miner",
	HandlerType: (*MinerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Miner_Ping_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Miner_Info_Handler,
		},
		{
			MethodName: "Handshake",
			Handler:    _Miner_Handshake_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Miner_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Miner_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "miner.proto",
}

func init() { proto.RegisterFile("miner.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdd, 0x4a, 0xeb, 0x40,
	0x10, 0x6e, 0xd2, 0xa6, 0x9c, 0x4c, 0xce, 0x29, 0x3d, 0x7b, 0x8e, 0x35, 0x84, 0x0a, 0x25, 0x8a,
	0x14, 0x91, 0x80, 0xf1, 0x46, 0x04, 0x2f, 0x05, 0x7b, 0x21, 0x84, 0xf4, 0x09, 0x52, 0xbb, 0xb6,
	0xa1, 0x69, 0x12, 0x37, 0x1b, 0x61, 0x1f, 0xc1, 0x77, 0xf4, 0x61, 0x64, 0x7f, 0xb2, 0x49, 0x2d,
	0xde, 0x65, 0x66, 0xbf, 0xf9, 0xe6, 0x9b, 0x6f, 0x26, 0xe0, 0xec, 0xd3, 0x1c, 0x93, 0xa0, 0x24,
	0x05, 0x2d, 0x90, 0x25, 0x02, 0xff, 0x0f, 0x38, 0x51, 0x9a, 0x6f, 0x62, 0xfc, 0x56, 0xe3, 0x8a,
	0xfa, 0xe7, 0x60, 0xcb, 0xb0, 0xcc, 0x18, 0x9a, 0xc0, 0xb0, 0xa2, 0x09, 0xad, 0x2b, 0xd7, 0x98,
	0x19, 0x73, 0x3b, 0x56, 0x11, 0xaf, 0x59, 0xe4, 0xaf, 0x45, 0x53, 0xe3, 0x80, 0x2d, 0xc3, 0x32,
	0x63, 0xfe, 0x05, 0x8c, 0x9f, 0x92, 0x7c, 0x5d, 0x6d, 0x93, 0x1d, 0x56, 0x00, 0x34, 0x86, 0xfe,
	0xb6, 0x5e, 0x29, 0x12, 0xfe, 0xe9, 0x5f, 0xc2, 0xa8, 0x83, 0xe2, 0xbd, 0xfe, 0x83, 0x14, 0xa4,
	0x50, 0x4a, 0x5d, 0x04, 0xbf, 0x97, 0x34, 0x21, 0xb4, 0x61, 0x1a, 0x81, 0x99, 0xae, 0x15, 0xc4,
	0x4c, 0xd7, 0xc8, 0x83, 0x5f, 0x04, 0x6f, 0xd2, 0x8a, 0x12, 0xe6, 0x9a, 0x22, 0xab, 0x63, 0xce,
	0x98, 0xee, 0x93, 0x0d, 0x76, 0xfb, 0x92, 0x51, 0x04, 0xfe, 0xa7, 0x01, 0xa0, 0x28, 0x79, 0xdb,
	0x29, 0xd8, 0x2f, 0x45, 0x4e, 0x93, 0x4e, 0xeb, 0x36, 0x81, 0x42, 0xb0, 0xa2, 0x82, 0xd0, 0xca,
	0x35, 0x67, 0xfd, 0xb9, 0x13, 0x4e, 0x03, 0x69, 0x60, 0x5b, 0x1f, 0x88, 0xe7, 0xc7, 0x9c, 0x12,
	0x16, 0x4b, 0xa8, 0x77, 0x05, 0x83, 0xb2, 0x20, 0x42, 0xea, 0x22, 0x6a, 0xa4, 0x2e, 0x22, 0x84,
	0x64, 0x5e, 0xc9, 0x14, 0xdf, 0x5e, 0x04, 0xd0, 0x12, 0x70, 0x9b, 0x76, 0x98, 0x35, 0x36, 0xed,
	0x30, 0x43, 0xd7, 0x60, 0xbd, 0x27, 0x59, 0x8d, 0x45, 0x91, 0x13, 0x4e, 0x8e, 0xfb, 0x73, 0x9a,
	0x58, 0x82, 0xee, 0xcd, 0x3b, 0xc3, 0x3f, 0x03, 0x67, 0x49, 0x8b, 0xf2, 0x07, 0xbf, 0xf8, 0xaa,
	0xe4, 0x73, 0x99, 0xb1, 0xf0, 0xc3, 0x04, 0xeb, 0x59, 0xcc, 0x19, 0xc0, 0x80, 0x6f, 0x1d, 0x21,
	0xd5, 0xa0, 0x73, 0x11, 0xde, 0xf8, 0x20, 0xc7, 0x57, 0xdc, 0xe3, 0x78, 0xbe, 0x71, 0x8d, 0xef,
	0x5c, 0x83, 0xc6, 0xb7, 0x27, 0xd1, 0x43, 0x0f, 0x60, 0xeb, 0x75, 0xa3, 0x53, 0x05, 0xf8, 0x7e,
	0x26, 0xde, 0xc9, 0xf1, 0x83, 0x2c, 0xbf, 0x01, 0x4b, 0x8c, 0x8c, 0xfe, 0x1d, 0x1a, 0x20, 0xcb,
	0xfe, 0x1e, 0xb9, 0x22, 0x15, 0xf2, 0x41, 0xb5, 0xc2, 0x8e, 0x29, 0x5a, 0xa1, 0x76, 0xc2, 0xef,
	0xad, 0x86, 0xe2, 0xa7, 0xb8, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x95, 0x7f, 0x28, 0xb4, 0x23,
	0x03, 0x00, 0x00,
}
