version: '2'

services:
  prometheus:
    image: prom/prometheus:0.18.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '-config.file=/etc/prometheus/prometheus.yaml'
    network_mode: "host"
  grafana:
    image: grafana/grafana:3.0.0-beta7
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    network_mode: "host"
