global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    target_groups:
        # Hub, Worker, Locator, Node.
        - targets: ['127.0.0.1:14000', '127.0.0.1:14001', '127.0.0.1:14002', '127.0.0.1:14003']