#!/bin/bash

set -e

case $1 in
    configure)
    	if ! getent passwd sonm >/dev/null; then
    	    useradd --user-group --no-create-home --shell /usr/sbin/nologin sonm
    	fi

        chown -R sonm /var/{lib,run}/sonm
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with an unknown argument \`$1'" >&2
        ;;
esac

#DEBHELPER#
        
exit 0
