// Code generated by protoc-gen-go. DO NOT EDIT.
// source: marketplace.proto

package sonm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetOrdersRequest struct {
	// Order keeps slot and type for searching
	Order *Order `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
	// Count describe how namy results must be returned (order by price)
	Count uint64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *GetOrdersRequest) Reset()                    { *m = GetOrdersRequest{} }
func (m *GetOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrdersRequest) ProtoMessage()               {}
func (*GetOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *GetOrdersRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *GetOrdersRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetOrdersReply struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *GetOrdersReply) Reset()                    { *m = GetOrdersReply{} }
func (m *GetOrdersReply) String() string            { return proto.CompactTextString(m) }
func (*GetOrdersReply) ProtoMessage()               {}
func (*GetOrdersReply) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *GetOrdersReply) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

// GetProcessingReply represent Node's local
// orders processing status
type GetProcessingReply struct {
	Orders map[string]*GetProcessingReply_ProcessedOrder `protobuf:"bytes,2,rep,name=orders" json:"orders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetProcessingReply) Reset()                    { *m = GetProcessingReply{} }
func (m *GetProcessingReply) String() string            { return proto.CompactTextString(m) }
func (*GetProcessingReply) ProtoMessage()               {}
func (*GetProcessingReply) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *GetProcessingReply) GetOrders() map[string]*GetProcessingReply_ProcessedOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

type GetProcessingReply_ProcessedOrder struct {
	Id        string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Status    uint32     `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Timestamp *Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Extra     string     `protobuf:"bytes,4,opt,name=extra" json:"extra,omitempty"`
}

func (m *GetProcessingReply_ProcessedOrder) Reset()         { *m = GetProcessingReply_ProcessedOrder{} }
func (m *GetProcessingReply_ProcessedOrder) String() string { return proto.CompactTextString(m) }
func (*GetProcessingReply_ProcessedOrder) ProtoMessage()    {}
func (*GetProcessingReply_ProcessedOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{2, 0}
}

func (m *GetProcessingReply_ProcessedOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetProcessingReply_ProcessedOrder) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetProcessingReply_ProcessedOrder) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GetProcessingReply_ProcessedOrder) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type TouchOrdersRequest struct {
	IDs []string `protobuf:"bytes,1,rep,name=IDs" json:"IDs,omitempty"`
}

func (m *TouchOrdersRequest) Reset()                    { *m = TouchOrdersRequest{} }
func (m *TouchOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*TouchOrdersRequest) ProtoMessage()               {}
func (*TouchOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *TouchOrdersRequest) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

func init() {
	proto.RegisterType((*GetOrdersRequest)(nil), "sonm.GetOrdersRequest")
	proto.RegisterType((*GetOrdersReply)(nil), "sonm.GetOrdersReply")
	proto.RegisterType((*GetProcessingReply)(nil), "sonm.GetProcessingReply")
	proto.RegisterType((*GetProcessingReply_ProcessedOrder)(nil), "sonm.GetProcessingReply.ProcessedOrder")
	proto.RegisterType((*TouchOrdersRequest)(nil), "sonm.TouchOrdersRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Market service

type MarketClient interface {
	GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersReply, error)
	GetOrderByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Order, error)
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error)
	CancelOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Empty, error)
	TouchOrders(ctx context.Context, in *TouchOrdersRequest, opts ...grpc.CallOption) (*Empty, error)
	// GetProcessing returns currently processing orders
	// not required in Marketplace service
	// must be implemented on Node
	GetProcessing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetProcessingReply, error)
}

type marketClient struct {
	cc *grpc.ClientConn
}

func NewMarketClient(cc *grpc.ClientConn) MarketClient {
	return &marketClient{cc}
}

func (c *marketClient) GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersReply, error) {
	out := new(GetOrdersReply)
	err := grpc.Invoke(ctx, "/sonm.Market/GetOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetOrderByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := grpc.Invoke(ctx, "/sonm.Market/GetOrderByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := grpc.Invoke(ctx, "/sonm.Market/CreateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) CancelOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.Market/CancelOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) TouchOrders(ctx context.Context, in *TouchOrdersRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.Market/TouchOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) GetProcessing(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetProcessingReply, error) {
	out := new(GetProcessingReply)
	err := grpc.Invoke(ctx, "/sonm.Market/GetProcessing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Market service

type MarketServer interface {
	GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersReply, error)
	GetOrderByID(context.Context, *ID) (*Order, error)
	CreateOrder(context.Context, *Order) (*Order, error)
	CancelOrder(context.Context, *Order) (*Empty, error)
	TouchOrders(context.Context, *TouchOrdersRequest) (*Empty, error)
	// GetProcessing returns currently processing orders
	// not required in Marketplace service
	// must be implemented on Node
	GetProcessing(context.Context, *Empty) (*GetProcessingReply, error)
}

func RegisterMarketServer(s *grpc.Server, srv MarketServer) {
	s.RegisterService(&_Market_serviceDesc, srv)
}

func _Market_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetOrders(ctx, req.(*GetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetOrderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetOrderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/GetOrderByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetOrderByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).CancelOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_TouchOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).TouchOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/TouchOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).TouchOrders(ctx, req.(*TouchOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_GetProcessing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetProcessing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Market/GetProcessing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetProcessing(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Market_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonm.Market",
	HandlerType: (*MarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrders",
			Handler:    _Market_GetOrders_Handler,
		},
		{
			MethodName: "GetOrderByID",
			Handler:    _Market_GetOrderByID_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Market_CreateOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Market_CancelOrder_Handler,
		},
		{
			MethodName: "TouchOrders",
			Handler:    _Market_TouchOrders_Handler,
		},
		{
			MethodName: "GetProcessing",
			Handler:    _Market_GetProcessing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketplace.proto",
}

func init() { proto.RegisterFile("marketplace.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xed, 0xc4, 0xc2, 0x63, 0x9a, 0x86, 0x51, 0x55, 0x59, 0x3e, 0x05, 0x83, 0x68, 0x39,
	0x90, 0x43, 0x10, 0xa8, 0xe2, 0xe3, 0x02, 0xa9, 0xaa, 0x08, 0x21, 0xd0, 0xaa, 0x7f, 0x60, 0x63,
	0x8f, 0xc0, 0xaa, 0xbf, 0xd8, 0x5d, 0x23, 0x7c, 0xe0, 0x67, 0xc1, 0xef, 0x43, 0xde, 0x75, 0x82,
	0x9d, 0x34, 0xb7, 0x9d, 0x37, 0xef, 0xbd, 0xc9, 0xbc, 0x89, 0xe1, 0x51, 0xce, 0xc5, 0x1d, 0xa9,
	0x2a, 0xe3, 0x31, 0x2d, 0x2a, 0x51, 0xaa, 0x12, 0xc7, 0xb2, 0x2c, 0xf2, 0xd0, 0xdb, 0xa4, 0x89,
	0x01, 0xc2, 0xd3, 0xb4, 0x68, 0xa1, 0x22, 0xe5, 0x06, 0x88, 0x3e, 0xc1, 0xec, 0x86, 0xd4, 0x17,
	0x91, 0x90, 0x90, 0x8c, 0x7e, 0xd4, 0x24, 0x15, 0x3e, 0x86, 0x49, 0xd9, 0x02, 0x81, 0x35, 0xb7,
	0x2e, 0xfd, 0xa5, 0xbf, 0x68, 0x25, 0x0b, 0xcd, 0x61, 0xa6, 0x83, 0x67, 0x30, 0x89, 0xcb, 0xba,
	0x50, 0x81, 0x3d, 0xb7, 0x2e, 0xc7, 0xcc, 0x14, 0xd1, 0x2b, 0x98, 0xf6, 0xcc, 0xaa, 0xac, 0xc1,
	0x27, 0xe0, 0x6a, 0x81, 0x0c, 0xac, 0xb9, 0xb3, 0xef, 0xd5, 0xb5, 0xa2, 0x3f, 0x36, 0xe0, 0x0d,
	0xa9, 0xaf, 0xa2, 0x8c, 0x49, 0xca, 0xb4, 0xf8, 0x66, 0xb4, 0xef, 0x76, 0x5a, 0x5b, 0x6b, 0x9f,
	0x1a, 0xed, 0x21, 0xd3, 0xd8, 0xc9, 0xeb, 0x42, 0x89, 0x66, 0x6b, 0x1a, 0xfe, 0x86, 0x69, 0x47,
	0xa3, 0x44, 0xf7, 0x71, 0x0a, 0x76, 0x9a, 0xe8, 0x9d, 0x3c, 0x66, 0xa7, 0x09, 0x9e, 0x83, 0x2b,
	0x15, 0x57, 0xb5, 0xd4, 0x4b, 0x9c, 0xb0, 0xae, 0xc2, 0x17, 0xe0, 0xa9, 0x34, 0x27, 0xa9, 0x78,
	0x5e, 0x05, 0x8e, 0x8e, 0xe0, 0xd4, 0x8c, 0xbe, 0xdd, 0xc2, 0xec, 0x3f, 0xa3, 0x8d, 0x82, 0x7e,
	0x29, 0xc1, 0x83, 0xb1, 0x76, 0x36, 0x45, 0xb8, 0x01, 0xbf, 0xf7, 0xab, 0x70, 0x06, 0xce, 0x1d,
	0x35, 0xdd, 0xf0, 0xf6, 0x89, 0xef, 0x61, 0xf2, 0x93, 0x67, 0x35, 0xe9, 0xe1, 0xfe, 0xf2, 0xe2,
	0xe8, 0x72, 0xc3, 0x2d, 0x98, 0x51, 0xbd, 0xb1, 0xaf, 0xac, 0xe8, 0x19, 0xe0, 0x6d, 0x59, 0xc7,
	0xdf, 0x87, 0xd7, 0x9b, 0x81, 0xb3, 0x5e, 0x99, 0xbc, 0x3d, 0xd6, 0x3e, 0x97, 0x7f, 0x6d, 0x70,
	0x3f, 0xeb, 0xff, 0x06, 0xbe, 0x05, 0x6f, 0x77, 0x21, 0x3c, 0xdf, 0xcd, 0x1c, 0x38, 0x84, 0x67,
	0x07, 0x78, 0x95, 0x35, 0xd1, 0x08, 0x2f, 0xe0, 0xe1, 0x16, 0xfb, 0xd0, 0xac, 0x57, 0xf8, 0xc0,
	0xf0, 0xd6, 0xab, 0xb0, 0x7f, 0xd6, 0x68, 0x84, 0xcf, 0xc1, 0xff, 0x28, 0x88, 0x2b, 0x32, 0xc1,
	0xf7, 0xbb, 0xf7, 0x51, 0x79, 0x11, 0x53, 0x76, 0x9c, 0x7a, 0x9d, 0x57, 0xaa, 0x1d, 0xff, 0x1a,
	0xfc, 0xde, 0xba, 0x18, 0x74, 0x37, 0x39, 0x48, 0x60, 0x5f, 0x77, 0x05, 0x27, 0x83, 0x58, 0xb1,
	0xdf, 0x0f, 0x83, 0x63, 0xc1, 0x47, 0xa3, 0x8d, 0xab, 0xbf, 0x91, 0x97, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xef, 0xdd, 0x4e, 0x8a, 0x5a, 0x03, 0x00, 0x00,
}
