// Code generated by protoc-gen-go. DO NOT EDIT.
// source: miner.proto

package sonm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MinerInfoRequest struct {
}

func (m *MinerInfoRequest) Reset()                    { *m = MinerInfoRequest{} }
func (m *MinerInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*MinerInfoRequest) ProtoMessage()               {}
func (*MinerInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type MinerHandshakeRequest struct {
	Hub string `protobuf:"bytes,1,opt,name=hub" json:"hub,omitempty"`
}

func (m *MinerHandshakeRequest) Reset()                    { *m = MinerHandshakeRequest{} }
func (m *MinerHandshakeRequest) String() string            { return proto.CompactTextString(m) }
func (*MinerHandshakeRequest) ProtoMessage()               {}
func (*MinerHandshakeRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *MinerHandshakeRequest) GetHub() string {
	if m != nil {
		return m.Hub
	}
	return ""
}

type Limits struct {
	Cores  uint64 `protobuf:"varint,1,opt,name=cores" json:"cores,omitempty"`
	Memory uint64 `protobuf:"varint,2,opt,name=memory" json:"memory,omitempty"`
}

func (m *Limits) Reset()                    { *m = Limits{} }
func (m *Limits) String() string            { return proto.CompactTextString(m) }
func (*Limits) ProtoMessage()               {}
func (*Limits) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Limits) GetCores() uint64 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *Limits) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

type MinerHandshakeReply struct {
	Miner  string  `protobuf:"bytes,1,opt,name=miner" json:"miner,omitempty"`
	Limits *Limits `protobuf:"bytes,2,opt,name=limits" json:"limits,omitempty"`
}

func (m *MinerHandshakeReply) Reset()                    { *m = MinerHandshakeReply{} }
func (m *MinerHandshakeReply) String() string            { return proto.CompactTextString(m) }
func (*MinerHandshakeReply) ProtoMessage()               {}
func (*MinerHandshakeReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *MinerHandshakeReply) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *MinerHandshakeReply) GetLimits() *Limits {
	if m != nil {
		return m.Limits
	}
	return nil
}

type MinerStartRequest struct {
	Id            string                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Registry      string                  `protobuf:"bytes,2,opt,name=registry" json:"registry,omitempty"`
	Image         string                  `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	Auth          string                  `protobuf:"bytes,4,opt,name=auth" json:"auth,omitempty"`
	RestartPolicy *ContainerRestartPolicy `protobuf:"bytes,5,opt,name=restartPolicy" json:"restartPolicy,omitempty"`
	Resources     *ContainerResources     `protobuf:"bytes,6,opt,name=resources" json:"resources,omitempty"`
}

func (m *MinerStartRequest) Reset()                    { *m = MinerStartRequest{} }
func (m *MinerStartRequest) String() string            { return proto.CompactTextString(m) }
func (*MinerStartRequest) ProtoMessage()               {}
func (*MinerStartRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *MinerStartRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MinerStartRequest) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

func (m *MinerStartRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *MinerStartRequest) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *MinerStartRequest) GetRestartPolicy() *ContainerRestartPolicy {
	if m != nil {
		return m.RestartPolicy
	}
	return nil
}

func (m *MinerStartRequest) GetResources() *ContainerResources {
	if m != nil {
		return m.Resources
	}
	return nil
}

type MinerStartReply struct {
	Container string                          `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	Ports     map[string]*MinerStartReplyPort `protobuf:"bytes,2,rep,name=Ports" json:"Ports,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MinerStartReply) Reset()                    { *m = MinerStartReply{} }
func (m *MinerStartReply) String() string            { return proto.CompactTextString(m) }
func (*MinerStartReply) ProtoMessage()               {}
func (*MinerStartReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *MinerStartReply) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *MinerStartReply) GetPorts() map[string]*MinerStartReplyPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

type MinerStartReplyPort struct {
	IP   string `protobuf:"bytes,1,opt,name=IP" json:"IP,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
}

func (m *MinerStartReplyPort) Reset()                    { *m = MinerStartReplyPort{} }
func (m *MinerStartReplyPort) String() string            { return proto.CompactTextString(m) }
func (*MinerStartReplyPort) ProtoMessage()               {}
func (*MinerStartReplyPort) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5, 0} }

func (m *MinerStartReplyPort) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *MinerStartReplyPort) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type MinerStatusMapRequest struct {
}

func (m *MinerStatusMapRequest) Reset()                    { *m = MinerStatusMapRequest{} }
func (m *MinerStatusMapRequest) String() string            { return proto.CompactTextString(m) }
func (*MinerStatusMapRequest) ProtoMessage()               {}
func (*MinerStatusMapRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func init() {
	proto.RegisterType((*MinerInfoRequest)(nil), "sonm.MinerInfoRequest")
	proto.RegisterType((*MinerHandshakeRequest)(nil), "sonm.MinerHandshakeRequest")
	proto.RegisterType((*Limits)(nil), "sonm.Limits")
	proto.RegisterType((*MinerHandshakeReply)(nil), "sonm.MinerHandshakeReply")
	proto.RegisterType((*MinerStartRequest)(nil), "sonm.MinerStartRequest")
	proto.RegisterType((*MinerStartReply)(nil), "sonm.MinerStartReply")
	proto.RegisterType((*MinerStartReplyPort)(nil), "sonm.MinerStartReply.port")
	proto.RegisterType((*MinerStatusMapRequest)(nil), "sonm.MinerStatusMapRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Miner service

type MinerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Info(ctx context.Context, in *MinerInfoRequest, opts ...grpc.CallOption) (*InfoReply, error)
	Handshake(ctx context.Context, in *MinerHandshakeRequest, opts ...grpc.CallOption) (*MinerHandshakeReply, error)
	Start(ctx context.Context, in *MinerStartRequest, opts ...grpc.CallOption) (*MinerStartReply, error)
	Stop(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskReply, error)
	TasksStatus(ctx context.Context, opts ...grpc.CallOption) (Miner_TasksStatusClient, error)
}

type minerClient struct {
	cc *grpc.ClientConn
}

func NewMinerClient(cc *grpc.ClientConn) MinerClient {
	return &minerClient{cc}
}

func (c *minerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := grpc.Invoke(ctx, "/sonm.Miner/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Info(ctx context.Context, in *MinerInfoRequest, opts ...grpc.CallOption) (*InfoReply, error) {
	out := new(InfoReply)
	err := grpc.Invoke(ctx, "/sonm.Miner/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Handshake(ctx context.Context, in *MinerHandshakeRequest, opts ...grpc.CallOption) (*MinerHandshakeReply, error) {
	out := new(MinerHandshakeReply)
	err := grpc.Invoke(ctx, "/sonm.Miner/Handshake", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Start(ctx context.Context, in *MinerStartRequest, opts ...grpc.CallOption) (*MinerStartReply, error) {
	out := new(MinerStartReply)
	err := grpc.Invoke(ctx, "/sonm.Miner/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Stop(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskReply, error) {
	out := new(StopTaskReply)
	err := grpc.Invoke(ctx, "/sonm.Miner/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) TasksStatus(ctx context.Context, opts ...grpc.CallOption) (Miner_TasksStatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Miner_serviceDesc.Streams[0], c.cc, "/sonm.Miner/TasksStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &minerTasksStatusClient{stream}
	return x, nil
}

type Miner_TasksStatusClient interface {
	Send(*MinerStatusMapRequest) error
	Recv() (*StatusMapReply, error)
	grpc.ClientStream
}

type minerTasksStatusClient struct {
	grpc.ClientStream
}

func (x *minerTasksStatusClient) Send(m *MinerStatusMapRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *minerTasksStatusClient) Recv() (*StatusMapReply, error) {
	m := new(StatusMapReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Miner service

type MinerServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Info(context.Context, *MinerInfoRequest) (*InfoReply, error)
	Handshake(context.Context, *MinerHandshakeRequest) (*MinerHandshakeReply, error)
	Start(context.Context, *MinerStartRequest) (*MinerStartReply, error)
	Stop(context.Context, *StopTaskRequest) (*StopTaskReply, error)
	TasksStatus(Miner_TasksStatusServer) error
}

func RegisterMinerServer(s *grpc.Server, srv MinerServer) {
	s.RegisterService(&_Miner_serviceDesc, srv)
}

func _Miner_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Miner/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Miner/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Info(ctx, req.(*MinerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerHandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Miner/Handshake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Handshake(ctx, req.(*MinerHandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Miner/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Start(ctx, req.(*MinerStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.Miner/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Stop(ctx, req.(*StopTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_TasksStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MinerServer).TasksStatus(&minerTasksStatusServer{stream})
}

type Miner_TasksStatusServer interface {
	Send(*StatusMapReply) error
	Recv() (*MinerStatusMapRequest, error)
	grpc.ServerStream
}

type minerTasksStatusServer struct {
	grpc.ServerStream
}

func (x *minerTasksStatusServer) Send(m *StatusMapReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *minerTasksStatusServer) Recv() (*MinerStatusMapRequest, error) {
	m := new(MinerStatusMapRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Miner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonm.Miner",
	HandlerType: (*MinerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Miner_Ping_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Miner_Info_Handler,
		},
		{
			MethodName: "Handshake",
			Handler:    _Miner_Handshake_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Miner_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Miner_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TasksStatus",
			Handler:       _Miner_TasksStatus_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "miner.proto",
}

func init() { proto.RegisterFile("miner.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x13, 0x3b, 0x22, 0x13, 0x20, 0xed, 0xf4, 0x66, 0x4c, 0x1f, 0x2a, 0x8b, 0x87, 0x80,
	0x50, 0x54, 0x02, 0x8a, 0x80, 0x47, 0x50, 0x11, 0x91, 0xa8, 0x14, 0x9c, 0xfe, 0xc0, 0x36, 0x59,
	0x92, 0x55, 0x62, 0xaf, 0xd9, 0x5d, 0x23, 0xf9, 0x83, 0x91, 0xe0, 0x2f, 0xaa, 0xbd, 0x38, 0x71,
	0xdd, 0x3c, 0x65, 0xe6, 0xcc, 0x9c, 0x33, 0x97, 0x9d, 0x18, 0x7a, 0x29, 0xcb, 0xa8, 0x18, 0xe6,
	0x82, 0x2b, 0x8e, 0xbe, 0xe4, 0x59, 0x1a, 0xf5, 0x59, 0xa6, 0x7f, 0x33, 0x46, 0x2c, 0x1c, 0x23,
	0x1c, 0xde, 0xe8, 0xac, 0x49, 0xf6, 0x8b, 0x27, 0xf4, 0x77, 0x41, 0xa5, 0x8a, 0x5f, 0xc3, 0xa9,
	0xc1, 0xbe, 0x93, 0x6c, 0x21, 0x57, 0x64, 0x4d, 0x5d, 0x00, 0x0f, 0xa1, 0xbd, 0x2a, 0xee, 0x42,
	0xef, 0xd2, 0x1b, 0x74, 0x13, 0x6d, 0xc6, 0x63, 0xe8, 0xfc, 0x60, 0x29, 0x53, 0x12, 0x4f, 0x20,
	0x98, 0x73, 0x41, 0xa5, 0x89, 0xfa, 0x89, 0x75, 0xf0, 0x0c, 0x3a, 0x29, 0x4d, 0xb9, 0x28, 0xc3,
	0x96, 0x81, 0x9d, 0x17, 0xff, 0x84, 0xe3, 0x66, 0x89, 0x7c, 0x53, 0x6a, 0x11, 0xd3, 0xb3, 0x2b,
	0x61, 0x1d, 0x7c, 0x05, 0x9d, 0x8d, 0x29, 0x62, 0x44, 0x7a, 0xa3, 0xa7, 0x43, 0x3d, 0xc3, 0xd0,
	0x16, 0x4e, 0x5c, 0x2c, 0xfe, 0xeb, 0xc1, 0x91, 0xd1, 0x9c, 0x29, 0x22, 0x54, 0xd5, 0xf2, 0x73,
	0x68, 0xb1, 0x85, 0x93, 0x6b, 0xb1, 0x05, 0x46, 0xf0, 0x44, 0xd0, 0x25, 0x93, 0xca, 0xb5, 0xd4,
	0x4d, 0xb6, 0xbe, 0xae, 0xce, 0x52, 0xb2, 0xa4, 0x61, 0xdb, 0x56, 0x37, 0x0e, 0x22, 0xf8, 0xa4,
	0x50, 0xab, 0xd0, 0x37, 0xa0, 0xb1, 0xf1, 0x0b, 0x3c, 0x13, 0x54, 0xea, 0x3a, 0x53, 0xbe, 0x61,
	0xf3, 0x32, 0x0c, 0x4c, 0x63, 0x17, 0xb6, 0xb1, 0xaf, 0x3c, 0x53, 0x44, 0x77, 0x92, 0xd4, 0x73,
	0x92, 0x87, 0x14, 0x1c, 0x43, 0x57, 0x50, 0xc9, 0x0b, 0x31, 0xa7, 0x32, 0xec, 0x18, 0x7e, 0xf8,
	0x98, 0x6f, 0xe3, 0xc9, 0x2e, 0x35, 0xfe, 0xef, 0x41, 0xbf, 0x3e, 0xa7, 0xde, 0xdb, 0x05, 0x74,
	0xe7, 0x15, 0xc9, 0x0d, 0xbb, 0x03, 0x70, 0x0c, 0xc1, 0x94, 0x0b, 0xb3, 0xbe, 0xf6, 0xa0, 0x37,
	0xba, 0xb4, 0x55, 0x1a, 0x1a, 0x43, 0x93, 0x72, 0x9d, 0x29, 0x51, 0x26, 0x36, 0x3d, 0x7a, 0x03,
	0x7e, 0xce, 0x85, 0xd9, 0xe1, 0x64, 0x5a, 0xed, 0x70, 0x32, 0xd5, 0x1b, 0xd1, 0xb8, 0xdb, 0x9f,
	0xb1, 0xa3, 0x5b, 0x80, 0x9d, 0x80, 0x3e, 0x94, 0x35, 0x2d, 0xab, 0x43, 0x59, 0xd3, 0x12, 0xaf,
	0x20, 0xf8, 0x43, 0x36, 0x05, 0x75, 0x4f, 0x18, 0xed, 0xef, 0x41, 0x4b, 0x25, 0x36, 0xf1, 0x73,
	0xeb, 0xa3, 0x17, 0x9f, 0xbb, 0x4b, 0x9c, 0x29, 0xa2, 0x0a, 0x79, 0x43, 0x72, 0xf7, 0xac, 0xa3,
	0x7f, 0x2d, 0x08, 0x4c, 0x04, 0xdf, 0x82, 0x3f, 0x65, 0xd9, 0x12, 0x8f, 0xac, 0xa2, 0xb6, 0x5d,
	0x52, 0xd4, 0xaf, 0x43, 0xf9, 0xa6, 0x8c, 0x0f, 0xf0, 0x1d, 0xf8, 0xfa, 0xd2, 0xf1, 0xac, 0x56,
	0xbf, 0x76, 0xfa, 0x15, 0xc5, 0x42, 0x96, 0x72, 0x0d, 0xdd, 0xed, 0x95, 0xe2, 0xcb, 0x1a, 0xaf,
	0xf9, 0xf7, 0x88, 0x5e, 0xec, 0x0f, 0x5a, 0x99, 0x4f, 0x10, 0x98, 0x41, 0xf1, 0xfc, 0xf1, 0xe8,
	0x96, 0x7e, 0xba, 0x77, 0x27, 0xf1, 0x01, 0x7e, 0x00, 0x7f, 0xa6, 0x78, 0x8e, 0x2e, 0x41, 0xdb,
	0xb7, 0x44, 0xae, 0x2b, 0xde, 0x71, 0x13, 0xb6, 0xac, 0x6f, 0xd0, 0xd3, 0xae, 0xb4, 0xbb, 0x7b,
	0xd0, 0x79, 0x73, 0x9d, 0xd1, 0x49, 0x25, 0xb1, 0xc5, 0x8d, 0xc6, 0xc0, 0xbb, 0xf2, 0xee, 0x3a,
	0xe6, 0x43, 0xf1, 0xfe, 0x3e, 0x00, 0x00, 0xff, 0xff, 0x63, 0x77, 0x20, 0x72, 0x4e, 0x04, 0x00,
	0x00,
}
