// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package sonm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DealStatus int32

const (
	DealStatus_PENDING  DealStatus = 0
	DealStatus_APPROVED DealStatus = 1
	DealStatus_FINISHED DealStatus = 2
)

var DealStatus_name = map[int32]string{
	0: "PENDING",
	1: "APPROVED",
	2: "FINISHED",
}
var DealStatus_value = map[string]int32{
	"PENDING":  0,
	"APPROVED": 1,
	"FINISHED": 2,
}

func (x DealStatus) String() string {
	return proto.EnumName(DealStatus_name, int32(x))
}
func (DealStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

type TaskListRequest struct {
	// HubID is hub eth id;
	// If empty - collect task info from all hubs
	HubID string `protobuf:"bytes,1,opt,name=hubID" json:"hubID,omitempty"`
}

func (m *TaskListRequest) Reset()                    { *m = TaskListRequest{} }
func (m *TaskListRequest) String() string            { return proto.CompactTextString(m) }
func (*TaskListRequest) ProtoMessage()               {}
func (*TaskListRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *TaskListRequest) GetHubID() string {
	if m != nil {
		return m.HubID
	}
	return ""
}

type TaskListReply struct {
	Task []*TaskInfo `protobuf:"bytes,1,rep,name=task" json:"task,omitempty"`
}

func (m *TaskListReply) Reset()                    { *m = TaskListReply{} }
func (m *TaskListReply) String() string            { return proto.CompactTextString(m) }
func (*TaskListReply) ProtoMessage()               {}
func (*TaskListReply) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *TaskListReply) GetTask() []*TaskInfo {
	if m != nil {
		return m.Task
	}
	return nil
}

type Deal struct {
	BidID  string     `protobuf:"bytes,1,opt,name=BidID" json:"BidID,omitempty"`
	AskID  string     `protobuf:"bytes,2,opt,name=AskID" json:"AskID,omitempty"`
	Status DealStatus `protobuf:"varint,3,opt,name=status,enum=sonm.DealStatus" json:"status,omitempty"`
}

func (m *Deal) Reset()                    { *m = Deal{} }
func (m *Deal) String() string            { return proto.CompactTextString(m) }
func (*Deal) ProtoMessage()               {}
func (*Deal) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *Deal) GetBidID() string {
	if m != nil {
		return m.BidID
	}
	return ""
}

func (m *Deal) GetAskID() string {
	if m != nil {
		return m.AskID
	}
	return ""
}

func (m *Deal) GetStatus() DealStatus {
	if m != nil {
		return m.Status
	}
	return DealStatus_PENDING
}

type DealListRequest struct {
	Owner  string     `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	Status DealStatus `protobuf:"varint,2,opt,name=status,enum=sonm.DealStatus" json:"status,omitempty"`
}

func (m *DealListRequest) Reset()                    { *m = DealListRequest{} }
func (m *DealListRequest) String() string            { return proto.CompactTextString(m) }
func (*DealListRequest) ProtoMessage()               {}
func (*DealListRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *DealListRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DealListRequest) GetStatus() DealStatus {
	if m != nil {
		return m.Status
	}
	return DealStatus_PENDING
}

type DealListReply struct {
	Deal []*Deal `protobuf:"bytes,1,rep,name=deal" json:"deal,omitempty"`
}

func (m *DealListReply) Reset()                    { *m = DealListReply{} }
func (m *DealListReply) String() string            { return proto.CompactTextString(m) }
func (*DealListReply) ProtoMessage()               {}
func (*DealListReply) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

func (m *DealListReply) GetDeal() []*Deal {
	if m != nil {
		return m.Deal
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskListRequest)(nil), "sonm.TaskListRequest")
	proto.RegisterType((*TaskListReply)(nil), "sonm.TaskListReply")
	proto.RegisterType((*Deal)(nil), "sonm.Deal")
	proto.RegisterType((*DealListRequest)(nil), "sonm.DealListRequest")
	proto.RegisterType((*DealListReply)(nil), "sonm.DealListReply")
	proto.RegisterEnum("sonm.DealStatus", DealStatus_name, DealStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TaskManagement service

type TaskManagementClient interface {
	// List produces a list of all tasks running on different SONM nodes
	List(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListReply, error)
	// Start starts a task on given resource
	Start(ctx context.Context, in *HubStartTaskRequest, opts ...grpc.CallOption) (*TaskInfo, error)
	// Status produces a task status by their ID
	Status(ctx context.Context, in *ID, opts ...grpc.CallOption) (*TaskInfo, error)
	// Logs retrieves a task log (stdin/stderr) from given task
	Logs(ctx context.Context, in *ID, opts ...grpc.CallOption) (TaskManagement_LogsClient, error)
	// Stop stops a task by their IDd
	Stop(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error)
}

type taskManagementClient struct {
	cc *grpc.ClientConn
}

func NewTaskManagementClient(cc *grpc.ClientConn) TaskManagementClient {
	return &taskManagementClient{cc}
}

func (c *taskManagementClient) List(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListReply, error) {
	out := new(TaskListReply)
	err := grpc.Invoke(ctx, "/sonm.TaskManagement/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskManagementClient) Start(ctx context.Context, in *HubStartTaskRequest, opts ...grpc.CallOption) (*TaskInfo, error) {
	out := new(TaskInfo)
	err := grpc.Invoke(ctx, "/sonm.TaskManagement/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskManagementClient) Status(ctx context.Context, in *ID, opts ...grpc.CallOption) (*TaskInfo, error) {
	out := new(TaskInfo)
	err := grpc.Invoke(ctx, "/sonm.TaskManagement/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskManagementClient) Logs(ctx context.Context, in *ID, opts ...grpc.CallOption) (TaskManagement_LogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TaskManagement_serviceDesc.Streams[0], c.cc, "/sonm.TaskManagement/Logs", opts...)
	if err != nil {
		return nil, err
	}
	x := &taskManagementLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaskManagement_LogsClient interface {
	Recv() (*TaskLogsChunk, error)
	grpc.ClientStream
}

type taskManagementLogsClient struct {
	grpc.ClientStream
}

func (x *taskManagementLogsClient) Recv() (*TaskLogsChunk, error) {
	m := new(TaskLogsChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *taskManagementClient) Stop(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.TaskManagement/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskManagement service

type TaskManagementServer interface {
	// List produces a list of all tasks running on different SONM nodes
	List(context.Context, *TaskListRequest) (*TaskListReply, error)
	// Start starts a task on given resource
	Start(context.Context, *HubStartTaskRequest) (*TaskInfo, error)
	// Status produces a task status by their ID
	Status(context.Context, *ID) (*TaskInfo, error)
	// Logs retrieves a task log (stdin/stderr) from given task
	Logs(*ID, TaskManagement_LogsServer) error
	// Stop stops a task by their IDd
	Stop(context.Context, *ID) (*Empty, error)
}

func RegisterTaskManagementServer(s *grpc.Server, srv TaskManagementServer) {
	s.RegisterService(&_TaskManagement_serviceDesc, srv)
}

func _TaskManagement_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskManagementServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.TaskManagement/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskManagementServer).List(ctx, req.(*TaskListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskManagement_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HubStartTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskManagementServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.TaskManagement/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskManagementServer).Start(ctx, req.(*HubStartTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskManagement_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskManagementServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.TaskManagement/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskManagementServer).Status(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskManagement_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskManagementServer).Logs(m, &taskManagementLogsServer{stream})
}

type TaskManagement_LogsServer interface {
	Send(*TaskLogsChunk) error
	grpc.ServerStream
}

type taskManagementLogsServer struct {
	grpc.ServerStream
}

func (x *taskManagementLogsServer) Send(m *TaskLogsChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _TaskManagement_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskManagementServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.TaskManagement/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskManagementServer).Stop(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonm.TaskManagement",
	HandlerType: (*TaskManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _TaskManagement_List_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _TaskManagement_Start_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _TaskManagement_Status_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _TaskManagement_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _TaskManagement_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node.proto",
}

// Client API for DealManagement service

type DealManagementClient interface {
	// List produces a list of all deals made by client with given ID
	List(ctx context.Context, in *DealListRequest, opts ...grpc.CallOption) (*DealListReply, error)
	// Status produces a detailed info about deal with given ID
	Status(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Deal, error)
	// Finish finishes a deal with given ID
	Finish(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error)
}

type dealManagementClient struct {
	cc *grpc.ClientConn
}

func NewDealManagementClient(cc *grpc.ClientConn) DealManagementClient {
	return &dealManagementClient{cc}
}

func (c *dealManagementClient) List(ctx context.Context, in *DealListRequest, opts ...grpc.CallOption) (*DealListReply, error) {
	out := new(DealListReply)
	err := grpc.Invoke(ctx, "/sonm.DealManagement/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dealManagementClient) Status(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Deal, error) {
	out := new(Deal)
	err := grpc.Invoke(ctx, "/sonm.DealManagement/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dealManagementClient) Finish(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.DealManagement/Finish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DealManagement service

type DealManagementServer interface {
	// List produces a list of all deals made by client with given ID
	List(context.Context, *DealListRequest) (*DealListReply, error)
	// Status produces a detailed info about deal with given ID
	Status(context.Context, *ID) (*Deal, error)
	// Finish finishes a deal with given ID
	Finish(context.Context, *ID) (*Empty, error)
}

func RegisterDealManagementServer(s *grpc.Server, srv DealManagementServer) {
	s.RegisterService(&_DealManagement_serviceDesc, srv)
}

func _DealManagement_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealManagementServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DealManagement/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealManagementServer).List(ctx, req.(*DealListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DealManagement_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealManagementServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DealManagement/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealManagementServer).Status(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DealManagement_Finish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealManagementServer).Finish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.DealManagement/Finish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealManagementServer).Finish(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _DealManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonm.DealManagement",
	HandlerType: (*DealManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _DealManagement_List_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _DealManagement_Status_Handler,
		},
		{
			MethodName: "Finish",
			Handler:    _DealManagement_Finish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}

// Client API for HubManagement service

type HubManagementClient interface {
	// Status produse a detailed info about Hub
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// WorkersList prouces a list of connected Workers
	WorkersList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// WorkersStatus produces a detailed info about a Worker by their ID
	WorkersStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// WorkersUpdateProperties updates resource properties on Worker
	// with given ID
	WorkersUpdateProperties(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// CreateAskPlan allows to create rules
	// for creating Ask orders on Marketplace
	CreateAskPlan(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// RemoveAskPlan allows to remove rules
	// for creating Ask orders on Marketplace
	RemoveAskPlan(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// List produces a list of all running tasks on the Hub
	TaskList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Status produces a detailed info about task on the Hub
	StatusList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type hubManagementClient struct {
	cc *grpc.ClientConn
}

func NewHubManagementClient(cc *grpc.ClientConn) HubManagementClient {
	return &hubManagementClient{cc}
}

func (c *hubManagementClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.HubManagement/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubManagementClient) WorkersList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.HubManagement/WorkersList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubManagementClient) WorkersStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.HubManagement/WorkersStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubManagementClient) WorkersUpdateProperties(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.HubManagement/WorkersUpdateProperties", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubManagementClient) CreateAskPlan(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.HubManagement/CreateAskPlan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubManagementClient) RemoveAskPlan(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.HubManagement/RemoveAskPlan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubManagementClient) TaskList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.HubManagement/TaskList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubManagementClient) StatusList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/sonm.HubManagement/StatusList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HubManagement service

type HubManagementServer interface {
	// Status produse a detailed info about Hub
	Status(context.Context, *Empty) (*Empty, error)
	// WorkersList prouces a list of connected Workers
	WorkersList(context.Context, *Empty) (*Empty, error)
	// WorkersStatus produces a detailed info about a Worker by their ID
	WorkersStatus(context.Context, *Empty) (*Empty, error)
	// WorkersUpdateProperties updates resource properties on Worker
	// with given ID
	WorkersUpdateProperties(context.Context, *Empty) (*Empty, error)
	// CreateAskPlan allows to create rules
	// for creating Ask orders on Marketplace
	CreateAskPlan(context.Context, *Empty) (*Empty, error)
	// RemoveAskPlan allows to remove rules
	// for creating Ask orders on Marketplace
	RemoveAskPlan(context.Context, *Empty) (*Empty, error)
	// List produces a list of all running tasks on the Hub
	TaskList(context.Context, *Empty) (*Empty, error)
	// Status produces a detailed info about task on the Hub
	StatusList(context.Context, *Empty) (*Empty, error)
}

func RegisterHubManagementServer(s *grpc.Server, srv HubManagementServer) {
	s.RegisterService(&_HubManagement_serviceDesc, srv)
}

func _HubManagement_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubManagementServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.HubManagement/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubManagementServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubManagement_WorkersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubManagementServer).WorkersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.HubManagement/WorkersList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubManagementServer).WorkersList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubManagement_WorkersStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubManagementServer).WorkersStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.HubManagement/WorkersStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubManagementServer).WorkersStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubManagement_WorkersUpdateProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubManagementServer).WorkersUpdateProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.HubManagement/WorkersUpdateProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubManagementServer).WorkersUpdateProperties(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubManagement_CreateAskPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubManagementServer).CreateAskPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.HubManagement/CreateAskPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubManagementServer).CreateAskPlan(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubManagement_RemoveAskPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubManagementServer).RemoveAskPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.HubManagement/RemoveAskPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubManagementServer).RemoveAskPlan(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubManagement_TaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubManagementServer).TaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.HubManagement/TaskList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubManagementServer).TaskList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubManagement_StatusList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubManagementServer).StatusList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonm.HubManagement/StatusList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubManagementServer).StatusList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _HubManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonm.HubManagement",
	HandlerType: (*HubManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _HubManagement_Status_Handler,
		},
		{
			MethodName: "WorkersList",
			Handler:    _HubManagement_WorkersList_Handler,
		},
		{
			MethodName: "WorkersStatus",
			Handler:    _HubManagement_WorkersStatus_Handler,
		},
		{
			MethodName: "WorkersUpdateProperties",
			Handler:    _HubManagement_WorkersUpdateProperties_Handler,
		},
		{
			MethodName: "CreateAskPlan",
			Handler:    _HubManagement_CreateAskPlan_Handler,
		},
		{
			MethodName: "RemoveAskPlan",
			Handler:    _HubManagement_RemoveAskPlan_Handler,
		},
		{
			MethodName: "TaskList",
			Handler:    _HubManagement_TaskList_Handler,
		},
		{
			MethodName: "StatusList",
			Handler:    _HubManagement_StatusList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}

func init() { proto.RegisterFile("node.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc7, 0x93, 0x2e, 0x2b, 0xdd, 0x29, 0xfd, 0x90, 0x01, 0x51, 0x7a, 0x01, 0xc5, 0x42, 0x90,
	0x81, 0x54, 0x50, 0xb7, 0x3d, 0x40, 0x59, 0x3a, 0x1a, 0x69, 0x94, 0x90, 0xf2, 0x71, 0xc3, 0x8d,
	0xa3, 0x9a, 0x36, 0x4a, 0x62, 0x87, 0xd8, 0x01, 0xf5, 0x19, 0x78, 0x57, 0xc4, 0x23, 0x20, 0x27,
	0xa9, 0x12, 0xa2, 0x6d, 0xdd, 0x55, 0x7d, 0x8e, 0x7f, 0xfe, 0x9f, 0xff, 0x39, 0xa7, 0x0a, 0x00,
	0xe3, 0x2b, 0x3a, 0x8e, 0x13, 0x2e, 0x39, 0x32, 0x04, 0x67, 0xd1, 0xb0, 0xe7, 0x33, 0xf5, 0xcb,
	0x7c, 0x92, 0xa7, 0x87, 0xed, 0xc8, 0x67, 0x34, 0x29, 0x82, 0xa3, 0x4d, 0xea, 0xe5, 0x47, 0xfc,
	0x02, 0x7a, 0x9f, 0x88, 0x08, 0x2e, 0x7d, 0x21, 0x5d, 0xfa, 0x23, 0xa5, 0x42, 0xa2, 0xfb, 0x70,
	0xb8, 0x49, 0x3d, 0xdb, 0x1a, 0xe8, 0x23, 0xdd, 0x3c, 0x72, 0xf3, 0x00, 0x9f, 0x40, 0xa7, 0x04,
	0xe3, 0x70, 0x8b, 0x30, 0x18, 0x92, 0x88, 0x60, 0xa0, 0x8f, 0x0e, 0xcc, 0xf6, 0xa4, 0x3b, 0x56,
	0xf5, 0xc6, 0x0a, 0xb1, 0xd9, 0x77, 0xee, 0x66, 0x77, 0xf8, 0x1b, 0x18, 0x16, 0x25, 0xa1, 0x92,
	0x7c, 0xeb, 0xaf, 0x4a, 0xc9, 0x2c, 0x50, 0xd9, 0xa9, 0x08, 0x6c, 0x6b, 0xd0, 0xc8, 0xb3, 0x59,
	0x80, 0x4c, 0x68, 0x0a, 0x49, 0x64, 0x2a, 0x06, 0x07, 0x23, 0xdd, 0xec, 0x4e, 0xfa, 0xb9, 0xb2,
	0xd2, 0x59, 0x66, 0x79, 0xb7, 0xb8, 0xc7, 0x1f, 0xa1, 0xa7, 0xb2, 0x35, 0xef, 0xfc, 0x17, 0xa3,
	0xc9, 0xae, 0x50, 0x16, 0x54, 0x24, 0x1b, 0x7b, 0x24, 0x5f, 0x43, 0xa7, 0x94, 0x54, 0x5d, 0x3e,
	0x06, 0x63, 0x45, 0x49, 0x58, 0x74, 0x09, 0xe5, 0x43, 0x37, 0xcb, 0xbf, 0x3c, 0x03, 0x28, 0x65,
	0x50, 0x1b, 0xee, 0x38, 0xb3, 0x85, 0x65, 0x2f, 0xde, 0xf5, 0x35, 0x74, 0x17, 0x5a, 0x53, 0xc7,
	0x71, 0x3f, 0x7c, 0x99, 0x59, 0x7d, 0x5d, 0x45, 0x17, 0xf6, 0xc2, 0x5e, 0xce, 0x67, 0x56, 0xbf,
	0x31, 0xf9, 0xa3, 0x43, 0x57, 0xcd, 0xea, 0x3d, 0x61, 0x64, 0x4d, 0x23, 0xca, 0x24, 0x3a, 0x05,
	0x43, 0x95, 0x45, 0x0f, 0xca, 0x49, 0x56, 0x3a, 0x1b, 0xde, 0xab, 0xa7, 0xe3, 0x70, 0x8b, 0x35,
	0x74, 0x0a, 0x87, 0x4b, 0x49, 0x12, 0x89, 0x1e, 0xe5, 0xf7, 0xf3, 0xd4, 0xcb, 0x62, 0xc5, 0xed,
	0x9e, 0xd6, 0x76, 0x83, 0x35, 0xf4, 0x0c, 0x9a, 0x85, 0xe3, 0x56, 0x7e, 0x67, 0x5b, 0x57, 0x50,
	0xc7, 0x60, 0x5c, 0xf2, 0x75, 0x95, 0xa9, 0x9a, 0xe0, 0x6b, 0x71, 0xbe, 0x49, 0x59, 0x80, 0xb5,
	0x37, 0x3a, 0x7a, 0x02, 0xc6, 0x52, 0xf2, 0xb8, 0x82, 0xb6, 0xf3, 0xd3, 0x2c, 0x8a, 0xe5, 0x16,
	0x6b, 0x93, 0xdf, 0x3a, 0x74, 0xd5, 0xa0, 0xae, 0x6f, 0xb8, 0xb6, 0xca, 0x5d, 0xad, 0xff, 0xd6,
	0x81, 0x35, 0x34, 0xba, 0xc2, 0x7a, 0x65, 0x2d, 0x58, 0x43, 0x4f, 0xa1, 0x79, 0xe1, 0x33, 0x5f,
	0x6c, 0xae, 0x77, 0xf3, 0xb7, 0x01, 0x9d, 0x79, 0xea, 0x55, 0xcc, 0x94, 0x13, 0xa9, 0xa2, 0xb5,
	0x77, 0xe8, 0x18, 0xda, 0x5f, 0x79, 0x12, 0xd0, 0x44, 0x64, 0xce, 0x6f, 0x42, 0x5f, 0x41, 0xa7,
	0x40, 0x6f, 0xa1, 0x7b, 0x06, 0x0f, 0x0b, 0xf8, 0x73, 0xbc, 0x22, 0x92, 0x3a, 0x09, 0x8f, 0x69,
	0x22, 0x7d, 0x2a, 0xf6, 0xd5, 0x38, 0x4f, 0x28, 0x91, 0x74, 0x2a, 0x02, 0x27, 0x24, 0x6c, 0x1f,
	0xec, 0xd2, 0x88, 0xff, 0xbc, 0x15, 0xfc, 0x1c, 0x5a, 0xbb, 0x7f, 0xda, 0x8d, 0x9c, 0x09, 0x90,
	0xb7, 0xb7, 0x8f, 0xf4, 0x9a, 0xd9, 0xf7, 0xe6, 0xe4, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70,
	0xd3, 0x6e, 0xdc, 0xac, 0x04, 0x00, 0x00,
}
